sonar.projectKey=DallasLaComb_DalTime
sonar.organization=dallaslacomb

sonar.sources=backend/src,frontend/src,e2e/src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/.aws-sam/**,frontend/src/environments/**,frontend/src/main.ts,frontend/android/**,frontend/ios/**

sonar.javascript.lcov.reportPaths=frontend/coverage/frontend/lcov.info,backend/coverage/lcov.info
