AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  PostShiftFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: postShift.handler
      Runtime: nodejs18.x
      CodeUri: .
      Environment:
        Variables:
          SUPABASE_URL: !Ref https://anqyuajrqxxyxusdpaoi.supabase.co
          SUPABASE_API_KEY: !Ref eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFucXl1YWpycXh4eXh1c2RwYW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2OTkyMDMsImV4cCI6MjA2MzI3NTIwM30.EUVCgqw2RV-ZenuHO0UClob5d1HUxFz-fkcfiIah4dk
      Events:
        PostShiftApi:
          Type: Api
          Properties:
            Path: /shifts
            Method: post

Parameters:
  SupabaseUrl:
    Type: String
  SupabaseApiKey:
    Type: String
