AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  SupabaseUrl:
    Type: String
    NoEcho: true
    Description: 'Your Supabase project URL'
  SupabaseAnonKey:
    Type: String
    NoEcho: true
    Description: 'Your Supabase anon key'
  SupabaseServiceRole:
    Type: String
    NoEcho: true
    Description: 'Your Supabase service role key'
  SupabaseDbUrl:
    Type: String
    NoEcho: true
    Description: 'Your Supabase database connection string'
  CorsOrigin:
    Type: String
    Default: '*'
    Description: 'Allowed CORS origin (e.g., https://app.mysite.com)'

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 128

Resources:
  ApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      CorsConfiguration:
        AllowOrigins:
          - !Ref CorsOrigin
        AllowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization

  RegisterUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: auth/register/handler.handler
      Environment:
        Variables:
          SUPABASE_DB_URL: !Ref SupabaseDbUrl
          SUPABASE_URL: !Ref SupabaseUrl
          SUPABASE_SERVICE_ROLE: !Ref SupabaseServiceRole
      Events:
        RegisterApi:
          Type: HttpApi
          Properties:
            Path: /auth/register
            Method: POST
            ApiId: !Ref ApiGateway

  LoginUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: auth/login/handler.handler
      Environment:
        Variables:
          SUPABASE_URL: !Ref SupabaseUrl
          SUPABASE_ANON_KEY: !Ref SupabaseAnonKey
          SUPABASE_SERVICE_ROLE: !Ref SupabaseServiceRole
      Events:
        LoginApi:
          Type: HttpApi
          Properties:
            Path: /auth/login
            Method: POST
            ApiId: !Ref ApiGateway

  PostShiftFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: shift-api/postShift/handler.handler
      Environment:
        Variables:
          SUPABASE_URL: !Ref SupabaseUrl
          SUPABASE_ANON_KEY: !Ref SupabaseAnonKey
      Events:
        PostShiftApi:
          Type: HttpApi
          Properties:
            Path: /shift/post
            Method: POST
            ApiId: !Ref ApiGateway
