AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  SupabaseUrl:
    Type: String
    NoEcho: true
  SupabaseAnonKey:
    Type: String
    NoEcho: true
  SupabaseServiceRole:
    Type: String
    NoEcho: true
  CorsOrigin:
    Type: String
    Description: Allowed CORS origin (e.g., "*" for local dev or a specific domain for prod)

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 128

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: ShiftSchedulerApi
      StageName: Prod
      Cors:
        AllowMethods:
          - POST
          - OPTIONS
        AllowOrigin: !Ref CorsOrigin
        AllowHeaders:
          - Content-Type
          - Authorization

  RegisterUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth/register/
      Handler: handler.handler
      Environment:
        Variables:
          SUPABASE_URL: !Ref SupabaseUrl
          SUPABASE_SERVICE_ROLE: !Ref SupabaseServiceRole
      Events:
        RegisterApi:
          Type: Api
          Properties:
            Path: /auth/register
            Method: ANY
            RestApiId: !Ref ApiGateway

  LoginUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth/login/
      Handler: handler.handler
      Environment:
        Variables:
          SUPABASE_URL: !Ref SupabaseUrl
          SUPABASE_ANON_KEY: !Ref SupabaseAnonKey
          SUPABASE_SERVICE_ROLE: !Ref SupabaseServiceRole
      Events:
        LoginApi:
          Type: Api
          Properties:
            Path: /auth/login
            Method: ANY
            RestApiId: !Ref ApiGateway

  PostShiftFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: shift-api/postShift/
      Handler: handler.handler
      Environment:
        Variables:
          SUPABASE_URL: !Ref SupabaseUrl
          SUPABASE_ANON_KEY: !Ref SupabaseAnonKey
      Events:
        PostShiftApi:
          Type: Api
          Properties:
            Path: /shift/post
            Method: ANY
            RestApiId: !Ref ApiGateway
