AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  SupabaseUrl:
    Type: String
    NoEcho: true
  SupabaseAnonKey:
    Type: String
    NoEcho: true
  SupabaseServiceRole:
    Type: String
    NoEcho: true

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 128

Resources:
  RegisterUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth/register/
      Handler: handler.handler
      Environment:
        Variables:
          SUPABASE_URL: !Ref SupabaseUrl
          SUPABASE_SERVICE_ROLE: !Ref SupabaseServiceRole
      Events:
        RegisterApi:
          Type: Api
          Properties:
            Path: /auth/register
            Method: ANY # Changed to ANY for better local CORS testing
            Cors:
              AllowMethods: "'POST,OPTIONS'"
              AllowOrigins: "'*'"
              AllowHeaders: "'Content-Type,Authorization'"

  LoginUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth/login/
      Handler: handler.handler
      Environment:
        Variables:
          SUPABASE_URL: !Ref SupabaseUrl
          SUPABASE_ANON_KEY: !Ref SupabaseAnonKey
      Events:
        LoginApi:
          Type: Api
          Properties:
            Path: /auth/login
            Method: ANY
            Cors:
              AllowMethods: "'POST,OPTIONS'"
              AllowOrigins: "'*'"
              AllowHeaders: "'Content-Type,Authorization'"

  PostShiftFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: shift-api/postShift/
      Handler: handler.handler
      Environment:
        Variables:
          SUPABASE_URL: !Ref SupabaseUrl
          SUPABASE_ANON_KEY: !Ref SupabaseAnonKey
      Events:
        PostShiftApi:
          Type: Api
          Properties:
            Path: /shift/post
            Method: ANY
            Cors:
              AllowMethods: "'POST,OPTIONS'"
              AllowOrigins: "'*'"
              AllowHeaders: "'Content-Type,Authorization'"
