name: Deploy Full Stack

on:
  push:
    branches: [master]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build Angular
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "frontend/dist/frontend"

      # Optional: fix content types
      # - name: Set proper content-types for index.html etc.
      #   run: aws s3 cp frontend/dist/frontend/ s3://${{ secrets.S3_BUCKET }}/ --recursive --acl public-read --content-type "text/html"
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-backend:
    runs-on: ubuntu-latest
    needs: deploy-frontend
    steps:
      - uses: actions/checkout@v4

      - name: Install AWS CLI & SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Deploy SAM app
        working-directory: backend
        run: |
          sam build
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
            --stack-name shift-scheduler-api \
            --capabilities CAPABILITY_IAM \
            --region us-east-1 \
            --s3-bucket ${{ secrets.SAM_DEPLOY_BUCKET }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
